export const config = {
  developer: {
    name: "Saima Khan",
    title: "Senior QA Automation Lead",
    bio: "A Senior QA Automation Engineer and Delivery Lead with 12+ years of experience delivering high-quality, scalable testing solutions across web, API, mobile, and cloud-based platforms.",
    avatar: "/projects/saima_khan_photo.webp",
  },
  social: {
    github: "SaimaKhan99",
    email: "saimakhan.official99@gmail.com",
    location: " -- ",

  },
  projects: [
    {
      id: 1,
      title: "Discovery Education",
      description: "Led QA automation and delivery for a large-scale learning platform serving 50M+ users, ensuring high-quality releases through automation, API testing, CI/CD integration, and UAT validation.",
      image: "/projects/project-1.webp",
      technologies: ["Python", "Cucumber", "Groovy", "Playwright", "AI-Assisted QA", "Selenium"],
      github: "#",
      demo: "#",
    },
    {
      id: 2,
      title: "FinTech",
      description: "Supported QA automation and release validation for enterprise applications with transactional and payment modules, ensuring reliable releases through automation, API testing, CI/CD integration, and UAT coordination.",
      image: "/projects/project-2.png",
      technologies: ["Selenium", "TestNG", "SQL", "Postman API", "AWS", "Java"],
      github: "#",
      demo: "#",
    },
    {
      id: 3,
      title: "Agentic AI–Driven QA Automation Framework",
      description: "Designed and implemented an agentic AI-driven QA framework to optimize test case generation, execution, and maintenance using autonomous agents integrated into modern automation workflows.",
      image: "/projects/project-3.png",
      technologies: ["Claude", "MCP Agents", "LLM", "n8n", "Workflows", "Python"],
      github: "#",
      demo: "#",
    },
    {
      id: 4,
      title: "CI/CD Pipeline for Automated Testing & Release Readiness",
      description: "Designed and integrated CI/CD pipelines to automate build, test, and regression workflows, enabling reliable releases through Jenkins-based automation and cloud-ready testing practices.",
      image: "/projects/project-4.png",
      technologies: ["Jenkins", "Kubernetes", "Docker", "AWS", "Azure", "GitHub Actions"],
      github: "#",
      demo: "#",
    },
    {
      id: 5,
      title: "PowerBI/Tableau",
      description: "Built dashboards using Power BI and Tableau to visualize QA metrics, test execution results, and release health, improving visibility for stakeholders and delivery teams.",
      image: "/projects/project-5.png",
      technologies: ["Python", "TensorFlow.js", "D3.js", "Next.js", "WebGL", "TypeScript"],
      github: "#",
      demo: "#",
    },
  ],
  skills: [
    { name: "Git", icon: "git" },
    { name: "AWS", icon: "aws" },
    { name: "TypeScript", icon: "typescript" },
    { name: "Python", icon: "python" },
    { name: "Selenium", icon: "selenium" },
    { name: "Cucumber", icon: "cucumber" },
    { name: "Groovy", icon: "groovy" },
    { name: "Jenkins", icon: "jenkins" },
    { name: "CI/CD", icon: "cicd" },
    { name: "TestNG", icon: "testng" },
    { name: "Playwright", icon: "playwright" },
    { name: "AI-Agents", icon: "ai" },
  ],
};

